imports:
  - {resource: autowire.yaml}

services:
  Wakeapp\Bundle\SystemStatusBundle\Controller\StatusController:
    public: true
    tags:
      - { name: 'controller.service_arguments' }

  Wakeapp\Bundle\SystemStatusBundle\Service\AuthService:
    autowire: true
    autoconfigure: true
    arguments:
      - '%system_status.api_key%'

  Wakeapp\Bundle\SystemStatusBundle\Service\SystemStatusService:
    autowire: true
    calls:
      - 'setLogger': [ '@monolog.logger.system_status' ]
    tags:
      - { name: 'monolog.logger', channel: 'system_status' }

  Wakeapp\Bundle\SystemStatusBundle\Command\SystemStatusCommand:
    autowire: true
    calls:
      - 'setLogger': [ '@monolog.logger.system_status' ]
    tags:
      - { name: 'monolog.logger', channel: 'system_status' }
      - { name: 'console.command', command: 'system:status' }

  Wakeapp\Bundle\SystemStatusBundle\Service\SystemStatusPartService:
    autowire: true
